version: 2
jobs:
  build:
    branches:
      only:
        - ownImplementation
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline
      - run: mvn integration-test